name: Playwright Tests
on:
    push:
        branches: [ main ]
jobs:
    playwrighttests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Run tests
              run:
                    echo "Start the shopping store application"
                    chmod +x ./shopping-store-linix-amd64
                    ./shopping-store-linix-amd64 &
                    echo "Install dependencties from lockfile"
                    npm ci
                    echo "Run playwright tests"
                    npm run test:ci